apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.currencyService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microservice-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.currencyService.name }}
spec:
  replicas: {{ .Values.currencyService.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.currencyService.name }}
      app.kubernetes.io/part-of: microservice-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.currencyService.name }}
        app.kubernetes.io/part-of: microservice-demo
    spec:
      {{- with .Values.currencyService }}
      {{- include "microservice-demo.faultInjection" . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Values.currencyService.name }}
          image: "{{ .Values.currencyService.image.repository }}:{{ .Values.currencyService.image.tag }}"
          ports:
            - containerPort: {{ .Values.currencyService.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.currencyService.service.port }}"
          resources:
            {{- toYaml .Values.currencyService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: {{ .Values.currencyService.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: {{ .Values.currencyService.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.currencyService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microservice-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.currencyService.name }}
spec:
  type: {{ .Values.currencyService.service.type }}
  ports:
    - port: {{ .Values.currencyService.service.port }}
      targetPort: {{ .Values.currencyService.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.currencyService.name }}
    app.kubernetes.io/part-of: microservice-demo 