apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microservice-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.gateway.name }}
  annotations:
    metoro.source.repository.base64: Z2l0aHViLmNvbS9tZXRvcm8taW8vbWV0b3JvLWRlYnVnZ2luZy1zY2VuYXJpbwo=
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      {{- include "microservice-demo.selectorLabels" .Values.gateway | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "microservice-demo.selectorLabels" .Values.gateway | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.gateway.name }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.gateway.service.port }}
          env:
            - name: PRODUCT_CATALOG_SERVICE
              value: "http://{{ .Values.productCatalog.name }}:{{ .Values.productCatalog.service.port }}"
            - name: CURRENCY_SERVICE
              value: "http://{{ .Values.currencyService.name }}:{{ .Values.currencyService.service.port }}"
            - name: AD_SERVICE
              value: "http://{{ .Values.adService.name }}:{{ .Values.adService.service.port }}"
            - name: CHECKOUT_SERVICE
              value: "http://{{ .Values.checkoutService.name }}:{{ .Values.checkoutService.service.port }}"
            - name: INVENTORY_SERVICE
              value: "http://{{ .Values.inventoryService.name }}:{{ .Values.inventoryService.service.port }}"
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: {{ .Values.gateway.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: {{ .Values.gateway.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microservice-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.gateway.name }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.gateway.name }}
    app.kubernetes.io/part-of: microservice-demo 