apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.inventoryService.replicas }}
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: {{ .Values.inventoryService.image }}
        ports:
        - containerPort: 8085
        env:
        - name: PORT
          value: "8085"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "otel-collector:4317"
        {{- if .Values.inventoryService.faultInject.enabled }}
        - name: FAULT_INJECT_LATENCY
          value: "{{ .Values.inventoryService.faultInject.latency }}"
        - name: FAULT_INJECT_ERROR_RATE
          value: "{{ .Values.inventoryService.faultInject.errorRate }}"
        {{- end }}
        resources:
          limits:
            memory: {{ .Values.inventoryService.resources.limits.memory }}
            cpu: {{ .Values.inventoryService.resources.limits.cpu }}
          requests:
            memory: {{ .Values.inventoryService.resources.requests.memory }}
            cpu: {{ .Values.inventoryService.resources.requests.cpu }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 5