apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Values.global.namespace }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

    exporters:
      otlphttp/metoro:
        endpoint: http://metoro-exporter.metoro.svc.cluster.local/api/v1/send/traces/ebpf
        traces_endpoint: http://metoro-exporter.metoro.svc.cluster.local/api/v1/send/traces/ebpf
        tls:
          insecure: true
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/metoro, logging]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microservice-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
      app.kubernetes.io/part-of: microservice-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: microservice-demo
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.88.0
          imagePullPolicy: Always
          ports:
            - containerPort: 4317 # OTLP gRPC
              name: otlp-grpc
            - containerPort: 4318 # OTLP HTTP
              name: otlp-http
            - containerPort: 8888 # Metrics
              name: metrics
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
          args:
            - --config=/etc/otel-collector-config.yaml
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microservice-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: otel-collector
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: otlp-http
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: microservice-demo 